### PR TITLE
Extended ctags with modules and type constructors

### PR DESCRIPTION
**Pull request by andys8**
Hi, I extended the configuration to support:
* module names
* type constructors names 

Feel free to add them to the plugin, or give feedback if there is room for improvements :)

### CODE REVIEW

**Comment by kbsymanz** [comment]
Hi, thanks for the PR.

I've been away from Elm for a while so excuse what may be an obvious question. But I wonder what the difference is between the type constructor names you added and the types that it already handled.

Also, it was not able to follow a module reference like "Data.SomeModuleName", where there is a nested module name. At least it didn't work for me.

Thanks,

Kurt

**Comment by andys8** [comment]
First of all: I improved the definitions, because they were not working with all the cases. The following explanation is based on the updated pull request. I'll try to elaborate, what the defintions should do.

### Type constructors

The currently existing `type` definition will match on the name of the type (green).

image

The type constructor `type-cons` will instead match on the constructor names, which are used in other files. A common example would be the update function which is using `Msg` type constructor names like `Increment` or `Decrement`.

```elm
type Msg
  = Increment
  | Decrement

update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1
```

image

image

The implementation only works as intended if it's not a single line, which is common with `elm-format` and long lists of type constructors, e.g. https://github.com/rtfeldman/elm-spa-example/blob/master/src/Main.elm#L110-L122


### Modules

It matches on the name of module definitions and ignores the package hierarchy. This will most likely be the name, when the module is used and referenced. So it's easy to jump to the module's implementation.

image

**Comment by kbsymanz** [comment]
Thanks for the detailed explanation. The type constructors worked great for me. I couldn't get the modules to work though, not sure why. I don't have time to dig into it right now but hopefully I will before the month is out. Sorry about the delay.

**Comment by andys8** [comment]
Hey, great. Can you provide an example with `elm-spa-example` where modules don't work and upload the ctags file?

**Comment by kbsymanz** [comment]
I found once case where the module is not being found. When the `exposing` keyword is not on the same line as the `module` keyword and there is no space after the module name itself, the tag is not picked up.

```
module Util
    exposing
        ( (=>)
        , DateFmt(..)
        , DateSep(..)
...
```

**Comment by andys8** [comment]
Thanks, nice find. I think you can't have this with `elm-format`. I think it has to do with line breaks. The definition works with https://regex101.com, but it doesn't get picked up Exuberant Ctags 5.8

I try to come up with a simpler definition, that matches all the cases.

image

**Comment by andys8** [comment]
@kbsymanz I changed the module regex and squashed the changes into a single commit.

**Comment by andys8** [comment]
Also added the case where the module is defined as `port module`.

image

**Comment by kbsymanz** [comment]
Thanks for your work on this PR.

**Pull request merged**
